### ISSUE TITLE
Add SK ssh key for Michal

### ISSUE THREAD

**Issue by oneswig** [stackhpc/terraform-bastion#66]

**Comment by mnasiadka** [comment]
I'm storing my ssh keys in Mac Secure Enclave - what FIDO keys will add to that?

**Comment by mnasiadka** [comment]
Actually it wasn't, with #81 it will.

**Comment by oneswig** [comment]
> I'm storing my ssh keys in Mac Secure Enclave - what FIDO keys will add to that?

... compliance with company security policy?

Exceptions are going to need review.

**Comment by mnasiadka** [comment]
> > I'm storing my ssh keys in Mac Secure Enclave - what FIDO keys will add to that?
> 
> 
> 
> ... compliance with company security policy?
> 
> 
> 
> Exceptions are going to need review.

Where is that policy documented?

**Comment by axelsimon** [comment]
Am i assuming correctly that you are using [Secretive](https://github.com/maxgoedjen/secretive) to create and manage the keys?

In terms of security, it's similar, with some downgrades. 
1. Strictly speaking you are going from something you have (cred ID file/laptop) + something you know (passphrase on cred ID file) + something you have (Yubikey) to only something you have (laptop) + something you know (password or passphrase on private key, not sure if passphrases are supported) or worse, something you have (laptop) + something you are (biometrics). Worse because something you are is also something you can't change, if you need to. (And the legal protections surrounding biometrics are not as clear cut as those surrounding things or speech. Is someone putting your smartphone or your laptop in front of your face even if you don't want to illegal?)
2. There is also an argument to be made for `ecdsa-sha2-nist-p256` being less safe than `ed25519` and Secure Enclave can't do `ed25519` from what i understand. 

Beyond these considerations, you also lose in flexibility. If your mac laptop is stolen or breaks, the keys in its Secure Enclave are gone. You can't have a backup of them by design (which is a good thing: you can't extract secrets from the Secure Enclave). So unlike with hardware security keys with non-discoverable SSH keys, you can't have a backup of the cred ID file that you can import on another laptop to keep working (assuming you have the associated Yubikey). By extension, this also means if disaster strikes and your laptop is out of order, until you get a new laptop, generate new keys in its Secure Enclave and we get these distributed to customers, you can't log in to any customer servers. This can be alleviated by having a backup SSH key on… a Yubikey (along with a backup of its cred ID file). Conveniently, Secretive has support for Yubikeys ;) (it's unclear if it can do non-discoverable SSH keys or not however)

From a company perspective, i don't think there is a way we can check from the server side that this key is really backed by a Secure Enclave because it doesn't appear differently than a regular on-disk ECDSA NIST curve key. Which ties in to what @oneswig is saying: it deviates from company policy and associated auditability for no specific reason that i can see :)

So i suppose the question can then be reversed, what do we gain from this alternative / exception?

**Comment by axelsimon** [comment]
One more thing, some of the reported [bugs](https://github.com/maxgoedjen/secretive/issues/550) in Secretive don't exactly fill me with confidence. This looks a lot more experimental than Yubikey-backed non-discoverable SSH keys, which is pretty mainstream at this point.

**Comment by axelsimon** [comment]
> Where is that policy documented?

It's in this [Google Doc](https://docs.google.com/document/d/1CwMWRmiPoYczOv04NiFSGvNJgXMkRNQrMoLZY0b1w8k/edit), which is being updated to reflect the changes which were presented this morning.

**Comment by mnasiadka** [comment]
Don't get me wrong - but I used that for some time now (since that was better than plain old passwordless keys) - and I used yubikey in my previous company (which I lost and had to go an awful process of replacing my ssh key everywhere).

Yubikey is more elastic if you don't loose it - or don't leave it at home when going to the office.

I'm happy to move - but:

If you plan company policy changes - you usually advertise them via mail to employees - especially that I lost internet connectivity in the middle of the call (and there are people that are on vacation).

Second of all - you write down how to use it.

Unless I'm blind and all of this is somewhere, but it magically didn't land in my mailbox.

**Comment by axelsimon** [comment]
> Don't get me wrong - but I used that for some time now (since that was better than plain old passwordless keys) - and I used yubikey in my previous company (which I lost and had to go an awful process of replacing my ssh key everywhere).

That's great. Storing SSH keys in a Secure Enclave is much better than directly on-disk.
Losing a Yubikey: if you read the [docs](https://wiki.stackhpc.com/doc/fido2-hardware-security-keys-ssh-and-more-bcf5d6HW9e), you'll see that we have two keys for this reason: to not be stuck when you lose one, which is very likely to happen. This is also why we are asking everyone to do everything twice, for each key. If you look at [other PRs](https://github.com/stackhpc/terraform-bastion/pull/78/files), you'll see people are providing two SSH keys for this reason.

> Yubikey is more elastic if you don't loose it - or don't leave it at home when going to the office.

Yes. Just like an office badge/ID card or a laptop. No difference here.

Regarding company policy change, we have been discussing this since the Design Summit, over a month ago. We are also asking people to start providing new SSH SK keys with a plan to have them all for the 1st of August and won't be removing any other keys before the 1st of September. So this is not exactly rushed or happening overnight.

I've called attention to the wiki page a couple times on Slack, asking for comments. I'm sorry if you feel i didn't make enough noise about it, but the information is out there.

**Comment by mnasiadka** [comment]
I might be not the best searcher in the world, but when I search Slack for yubikey - I don't get anything that makes any sense.
Well, I can get into the office without ID/badge because Spaces allows you to open the door with your phone ;-)

Discussing is one thing, changing company policy without informing employees is another thing - maybe I just live in a different world than the rest of the company.
It's not only that change, it can be any change in the company policy - if you don't know it happened as an employee - well...

Updated the PR.
